# Generated by Django 4.2 on 2023-04-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_caterogy_tag_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caterogy',
            new_name='Category',
        ),
    ]
